### ISSUE TITLE
Move to v1.0.0

### ISSUE THREAD

**Issue by benjamind** [adobe/lit-mobx#37]
I'm not sure exactly when to bump this up to a 1.0.0 release. I don't actually intend to change the interface here at all, and I don't think there's much more to be done in terms of optimization internally.

I expect the next major changes will come with MobX 6, and future major version of lit-element. 

Should we just push to 1.0? Is there any benefit other than for people to feel more comfortable using a v1 project in production?

**Comment by Westbrook** [comment]
Is MobX 6 looking that something that would happen soon(ish)? That would be the only thing that gave me pause, but a schedule of anything more than 3 or 4 months is the same as a whole year, IMO.

While `lit-html` is looking to go 2.0, I know they are working to make that not a breaking change to `lit-element`. So, I don't think we'd need to wait in that area...

With #38 our test suite is more "complete" for cross-browser testing, so I'd say we'd good to go. Nothing wrong with a 2.0 in the next year if anything crazy happened between now and then, right?

**Comment by benjamind** [comment]
I think MobX 6 is a couple of months or more away. So maybe yeah we should just go to 1.0 now.

**Comment by jordanaustin** [comment]
It's always easier to sell team members on 1.0 vs. 0.x. From my standpoint I'd love to see this as a v1.0 since it seems very stable already. Just my 2¢ as a very new user of this project looking to fully integrate this into all of our applications. 

Thanks for a great project, it's a really simple and amazing addition to MobX for us LitElement users! 🎉

**Comment by benjamind** [comment]
Done!
