### ISSUE TITLE
Investigate more optimal approach to avoid closure creation in update

### ISSUE THREAD

**Issue by benjamind** [adobe/lit-mobx#6]
@justinfagnani pointed out in [this comment](https://github.com/adobe/lit-mobx/pull/5#discussion_r325838531) that we are creating a new closure on each update in order to update the tracked function in the Reaction. This is less than optimal but is currently the only approach while we depend upon the Reaction class implementation.

We should investigate using lower level functions from mobx to more tightly control our update tracking. We could for instance call [`trackDerivedFunction`](https://github.com/mobxjs/mobx/blob/1952e484b936ceb267d7aa4229510cf4431688fb/src/core/reaction.ts#L136) directly and not use the Reaction class at all, this may let us come up with a more optimal solution that avoids the closure creation on every update.

**Comment by benjamind** [comment]
Agreed I would like that transactional approach in mobx. Not sure it's currently easy to achieve though.

For now we've sidestepped the closure issue by more correctly tracking the `performUpdate` moment which we could cache so there's no more closure creation on update.

I'll leave this issue open however as I think taking a second look at the mobx integration at a later date would be a good thing anyway. Would love to get @mweststrate to chime in sometime.

**Comment by mweststrate** [comment]
I think theoretically something like this could be done (with better names). But unless there is provable overhead, as closure are really cheap nowadays, I'd call it over engineering ;)

```javascript
private trackingState: { current: PropertyValues, result } = { }

private trackable = () => {
  this.trackingState.result = super.update(this.trackingState.current)
}

protected update(changedProperties: PropertyValues): void {
            this.trackingState.current = changedProperties
            if (this[reactionSymbol]) {
                this[reactionSymbol].track(this.trackable);
            }
            return this.trackingState.result;
        }
```

**Comment by justinfagnani** [comment]
I agree it's not a pressing issue, but when you're dealing with potentially thousands of elements on a page, on devices with ~300MB of working memory and anemic processors (Android Go, KaiOS, etc.), every reference, microtask, and GC'ed object counts. As a personal rule, I try to limit per-element references and garbage where relatively easy... at the very least there's no harm.

What I like about the `startTrack`/`endTrack` approach is that it doesn't require caching long-lived references to additional closures and state, which may indeed be worse than transient closures since they become part of the old generation, rather than the cheap young generation, in generational GCs.

**Comment by mweststrate** [comment]
Yeah, for a library like this it might actually make a lot of sense (sorry,
didn't look at the context of this issue at all before :-P). Actually that
ref object might be a module constant, rather than an instance property,
making it even cheaper.

startTrack / endTrack is more try, as it exposes mobx to implementation
flaws; if things aren't properly finalized, the internal state of MobX
would really go haywire. But I don't think with the above approach there
would be any gain anymore anyway, as I don't think from top of my head that
mobx creates additional closures internally

**Comment by benjamind** [comment]
@mweststrate would MobX 6 change any of the reasoning above, or open new possibilities for other ways for this to be optimized (not that its slow right now), but just interested to see if this changes at all for MobX 6?

**Comment by mweststrate** [comment]
nope

**Comment by benjamind** [comment]
Ok then I am closing this issue, we can re-open if performance ever becomes a concern or new changes in lit-element / lit-html / mobx in the future give us other opportunities for improvement.
